apiVersion: v1

kind: ConfigMap


metadata:

  name: {{ include "edc.fullname" . }}



data:


  ENVIRONMENT:

    {{ .Values.environment.name | quote }}


  NAMESPACE:

    {{ .Values.environment.namespace | quote }}



  DB_HOST:

    {{ .Release.Name }}-postgresql