apiVersion: networking.k8s.io/v1

kind: Ingress


metadata:

  name: {{ include "edc.fullname" . }}



spec:

  ingressClassName:

    {{ .Values.ingress.className }}



  rules:


  - host:

      {{ .Values.ingress.host }}


    http:


      paths:


      - path: /

        pathType: Prefix


        backend:


          service:


            name:

              {{ include "edc.fullname" . }}


            port:


              number:

                {{ .Values.service.port }}