apiVersion: v1

kind: Secret


metadata:

  name: {{ include "edc.fullname" . }}



type: Opaque


stringData:


  DB_USER:

    {{ .Values.database.user }}


  DB_PASSWORD:

    postgres


  DB_NAME:

    {{ .Values.database.name }}